name: "Packages - action"

on:
  pull_request:

jobs:
  dotnet-outdated:
    name: "dotnet outdated"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mcld/dotnet-outdated-action@v1
